<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-17T01:11:50 EET" name="Tests" finished-at="2024-01-17T01:12:02 EET" duration-ms="11824">
    <groups>
    </groups>
    <test started-at="2024-01-17T01:11:50 EET" name="Test1" finished-at="2024-01-17T01:12:02 EET" duration-ms="11824">
      <class name="testcases.tests.RegisterUser">
        <test-method signature="visibleVerify()[pri:0, instance:testcases.tests.RegisterUser@299266e2]" started-at="2024-01-17T01:11:50 EET" name="visibleVerify" finished-at="2024-01-17T01:11:53 EET" duration-ms="2509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- visibleVerify -->
        <test-method signature="signUp()[pri:0, instance:testcases.tests.RegisterUser@299266e2]" started-at="2024-01-17T01:11:53 EET" name="signUp" finished-at="2024-01-17T01:12:01 EET" depends-on-methods="testcases.tests.RegisterUser.visibleVerify" duration-ms="7858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.tests.RegisterUser@299266e2]" started-at="2024-01-17T01:12:02 EET" name="tearDown" finished-at="2024-01-17T01:12:02 EET" duration-ms="202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.tests.RegisterUser -->
      <class name="testcases.tests.DeleteAccount">
        <test-method signature="deleteAccount()[pri:0, instance:testcases.tests.DeleteAccount@5471388b]" started-at="2024-01-17T01:12:01 EET" name="deleteAccount" finished-at="2024-01-17T01:12:02 EET" duration-ms="1425" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[account delete isnt seen expected [null] but found [org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //b[normalize-space()='Account Created!'' (tried for 1 second(s) with 500 milliseconds interval)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: account delete isnt seen expected [null] but found [org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //b[normalize-space()='Account Created!'' (tried for 1 second(s) with 500 milliseconds interval)]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotSame(Assert.java:965)
at org.testng.Assert.assertNull(Assert.java:898)
at testcases.components.AbstractComponent.assertVisible(AbstractComponent.java:37)
at testcases.tests.DeleteAccount.deleteAccount(DeleteAccount.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteAccount -->
      </class> <!-- testcases.tests.DeleteAccount -->
    </test> <!-- Test1 -->
  </suite> <!-- Tests -->
</testng-results>
